### PR TITLE
Add /about page info

### PR DESCRIPTION
**Pull request by alexgibson**
I took a stab at a basic /about page - it lists the sites/services we work on, and also lists everyone on the team. I don't think I've forgotten any thing/one but it's still early in the morning.

Also, if anyone would rather not have their job titles listed so formally, we could totally go with some comedy ones (like people use on phonebook?). Any typos or errors or other suggestions please let me know. If people would like their name linked to any personal blog / bio / profile please specify. Thanks!

### CODE REVIEW

**Comment by alexgibson** [comment]
cc/ @pmac @bensternthal @craigcook @metadave @glogiotatidis @jwhitlock @jpetto @jgmize @escattone @schalkneethling @stephaniehobson

**Comment by metadave** [comment]
looks good!

**Comment by bensternthal** [comment]
I plan to use A LOT of marketing jargon.

**Comment by alexgibson** [comment]
> I plan to use A LOT of marketing jargon.

fry

**Comment by stephaniehobson** [comment]
Since our audience is not other devs probably keeping our official job titles is the better way to go.👍

**Comment by jgmize** [comment]
Thanks @alexgibson -- I'm going to go ahead and merge this as-is, and anyone who wants to give themselves a fancier title and/or insert marketing jargon can open up a follow-up PR ;)

**Comment by pmac** [comment]
@alexgibson thanks! just fyi, you can use `(at)mozilla/meao` to ping us all :) Should be easier.

**Pull request merged**
