### PR TITLE
docker-run.sh works, it just is real slow now

### PR DESCRIPTION
**Pull request by jwhitlock**
Update docs so macOS users don't give up.

### CODE REVIEW

**Comment by jwhitlock** [comment]
It takes 134 seconds with ``:cached``, vs 137 seconds without.  Most of that time is spent in a ``chown`` of the current directory:

https://github.com/jekyll/docker/blob/73f933dd38c172b5af7ba2a4f76886cbe3f3ca96/repos/jekyll/copy/all/usr/local/bin/jekyll#L13

**Comment by metadave** [comment]
:+1:

**Comment by pmac** [comment]
Seems like maybe we should build our own image for this then. It can just
be run as the current local user and you won’t have to do any of that. But
that’s for later. This change seems fine to me too.
-- 
-- pmac

**Comment by jwhitlock** [comment]
I think the ``chown`` would be trivial if it was just processing the ~150 blog files, and not also the ~500 ``.git`` files and the 4351 ``vendor`` files.  Maybe we could use some creative mounting to avoid that.

**Pull request merged**
