### PR TITLE
Kuma Report, November 2017

### PR DESCRIPTION
**Pull request by jwhitlock**
Here's the sections this month, along with people that may want to suggest changes:

- Shipped the first 21 interactive examples (@schalkneethling, @stephaniehobson)
- Added browser versions, list-style-type, and even more Browser Compatibility Data (@Elchi3)
- Shipped a sticky table of contents and other article improvements (@stephaniehobson)
- Improved MDN in AWS and Kubernetes (@escattone, @jgmize)
- Shipped tweaks and fixes

I plan on publishing Tuesday, December 5th. I'm leaving the article in `_drafts` until then, in case you want to run `meao` locally.

### CODE REVIEW

**Comment by schalkneethling** [comment]
> Shipped the first 21 interactive examples

This definitely also involved @wbamber and @maboa

**Comment by Elchi3** [comment]
Great report, thanks John!

**Comment by jwhitlock** [comment]
@schalkneethling I think you mean @wbamberg. More reviews are welcome.

**Comment by jwhitlock** [comment]
Thanks for the reviews, publishing!

**Pull request merged**
