### PR TITLE
Kuma Report, August 2017

### PR DESCRIPTION
**Pull request by jwhitlock**
It's another long one.  I'm planning on merging tomorrow, after the SRE report.

@stephaniehobson or @schalkneethling may want to review the Interactive Examples section. @escatonne and @metadave may want to review the AWS migration section. @Elchi3 and @wbamberg may want to look at the BCD section.

### CODE REVIEW

**Comment by metadave** [comment]
+1 for the AWS update

**Comment by metadave** [comment]
+1 for the AWS update

**Comment by Elchi3** [comment]
Great summary and good reminder of how busy everyone actually was and is! Thanks!

I'm not familiar with the escaping here, but  `{{'{{'}}compat}}` looks odd.

**Comment by jwhitlock** [comment]
Yes, and it looks fine in Sphinx but bad in Markdown.  Sphinx / Jinja2 uses ``{{ }}`` as its macro syntax, so ``{{compat}}`` means "Call the template macro "compat", which doesn't exist, so return an empty string". I used the [Jinja2 trick](http://jinja.pocoo.org/docs/2.9/templates/#escaping) "{{'{{'}}" to return the string ``{{``, so the output is ``{{compat}}``.

**Comment by wbamberg** [comment]
In this bit:

> We're starting with showing them to 50% of anonymous users, to measure the difference in site speed. You can also visit the new pages directly. See the interactive editors in beta post on Discourse for more details, and to give your feedback.

... you might want to say that we are also showing a very short survey in pages that include this feature, and that filling in this survey is a great way to give us feedback.

**Comment by jwhitlock** [comment]
Thanks for the suggestion, @wbamberg. I've updated the paragraph. Publishing! 🚢

**Pull request merged**
